Giteaにのりかえ
Co-authored-by: ikura-hamu <104292023+ikura-hamu@users.noreply.github.com>
Reviewed-on: https://git.trap.jp/ikura-hamu/members/pulls/1

diff --git a/.github/workflows/plan.yml b/.github/workflows/plan.yml
--- a/.github/workflows/plan.yml
+++ b/.github/workflows/plan.yml
@@ -4,7 +4,7 @@ on:
   pull_request:
     branches:
       - main
-  workflow_dispatch:
+  workflow_dispatch: # Giteaでは無効 https://docs.gitea.com/usage/actions/comparison#workflow_dispatch
 
 permissions:
   pull-requests: write
@@ -40,14 +40,15 @@ jobs:
       - name: Terraform plan
         id: plan
         run: terraform plan -no-color -input=false
-        continue-on-error: true
+        continue-on-error: true # Giteaでは無効 https://docs.gitea.com/usage/actions/comparison#jobsjob_idcontinue-on-error
         env:
           GOOGLE_BACKEND_CREDENTIALS: ${{ secrets.GOOGLE_BACKEND_CREDENTIALS }}
-          GITHUB_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
+          GITHUB_TOKEN: ${{ secrets.GH_PERSONAL_TOKEN }}
 
       - name: Comment PR
         uses: actions/github-script@v7
         with:
+          base-url: https://git.trap.jp/api/v1
           script: |
             const message = `${{ steps.plan.outputs.stdout }}`;
             let filteredMessage = "`terraform plan`\n```\n" + message.split('\n').filter(line => !line.includes('Refreshing state...')).filter(line => !line.includes('Note:')).join('\n') + "\n```";
@@ -66,6 +67,7 @@ jobs:
             })
           github-token: ${{ secrets.GITHUB_TOKEN }}
 
-      - name: Check if plan was successful
-        if: steps.plan.outcome == 'failure'
-        run: exit 1
+      # Giteaでは起きない(continue-on-errorが使えないため)
+      # - name: Check if plan was successful
+      #   if: steps.plan.outcome == 'failure'
+      #   run: exit 1
